on: [push, pull_request]
jobs:
    clang-tidy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
            - working-directory: 2021/Robot2021/
              run: ./gradlew installRoboRioToolchain
            - working-directory: 2021/Robot2021/
              run: ./gradlew generateCompileCommands
            - working-directory: 2021/Robot2021/
              run: run-clang-tidy -fix -format -checks='bugprone-*,cert-*,clang-analyzer-*,concurrency-*,cppcoreguidelines-*,-cppcoreguidelines-pro-type-vararg,hicpp-*,-hicpp-vararg,misc-*,modernize-*,-modernize-use-trailing-return-type,performance-*,-readability-*' -p build/compile_commands/linuxx86-64/
            - name: Show fixes
              run: git diff
